# Generated by Django 3.2.8 on 2021-11-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211119_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kakao_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
