# Generated by Django 3.2.8 on 2021-10-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NursingInterventionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='NursingKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('DISEASE', 'Disease'), ('DIAGNOSIS', 'Diagnosis')], max_length=20)),
                ('connection', models.ManyToManyField(blank=True, related_name='_nursing_knowledges_nursingknowledge_connection_+', to='nursing_knowledges.NursingKnowledge')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeInterventionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_diagnosis', to='nursing_knowledges.nursingknowledge')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_diseases', to='nursing_knowledges.nursingknowledge')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_content', to='nursing_knowledges.nursinginterventioncontent')),
            ],
        ),
    ]
