# Generated by Django 3.2.8 on 2022-03-10 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisLargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisMediumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('diagnosis_large_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_medium_categories', to='nursing_knowledges.diagnosislargecategory')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisRelatedDiagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisSmallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField(blank=True, default='', max_length=3000)),
                ('intervention_content', models.TextField(blank=True, default='', max_length=3000)),
                ('diagnosis_medium_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_medium_categories', to='nursing_knowledges.diagnosismediumcategory')),
                ('related_diagnoses', models.ManyToManyField(blank=True, through='nursing_knowledges.DiagnosisRelatedDiagnoses', to='nursing_knowledges.DiagnosisSmallCategory')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseLargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseMediumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('disease_large_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_medium_categories', to='nursing_knowledges.diseaselargecategory')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseSmallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField(blank=True, default='', max_length=3000)),
                ('cause', models.TextField(blank=True, default='', max_length=3000)),
                ('symptom', models.TextField(blank=True, default='', max_length=3000)),
                ('diagnosis_and_checkup', models.TextField(blank=True, default='', max_length=3000)),
                ('treatment', models.TextField(blank=True, default='', max_length=3000)),
                ('nursing', models.TextField(blank=True, default='', max_length=3000)),
                ('disease_large_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_small_categories_by_large', to='nursing_knowledges.diseaselargecategory')),
                ('disease_medium_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_small_categories_by_medium', to='nursing_knowledges.diseasemediumcategory')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosissmallcategory')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasesmallcategory')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisToOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosissmallcategory')),
                ('disease_medium_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasemediumcategory')),
                ('disease_small_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasesmallcategory')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosisrelateddiagnoses',
            name='from_diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_diagnosis', to='nursing_knowledges.diagnosissmallcategory'),
        ),
        migrations.AddField(
            model_name='diagnosisrelateddiagnoses',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_related_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosisrelateddiagnoses',
            name='to_diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_diagnosis', to='nursing_knowledges.diagnosissmallcategory'),
        ),
        migrations.CreateModel(
            name='DiagnosisInterventionAlpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=3000)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alphas', to='nursing_knowledges.diagnosissmallcategory')),
                ('disease_medium_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasemediumcategory')),
                ('disease_small_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasesmallcategory')),
            ],
        ),
    ]
