# Generated by Django 3.2.8 on 2021-10-21 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection', models.ManyToManyField(blank=True, related_name='_nursing_knowledges_diagnosis_connection_+', to='nursing_knowledges.Diagnosis')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection', models.ManyToManyField(blank=True, related_name='_nursing_knowledges_disease_connection_+', to='nursing_knowledges.Disease')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='nursingknowledge',
            name='connection',
        ),
        migrations.RenameModel(
            old_name='NursingInterventionContent',
            new_name='InterventionContent',
        ),
        migrations.DeleteModel(
            name='KnowledgeInterventionRelation',
        ),
        migrations.DeleteModel(
            name='NursingKnowledge',
        ),
        migrations.AddField(
            model_name='interventionrelation',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_relations', to='nursing_knowledges.interventioncontent'),
        ),
        migrations.AddField(
            model_name='interventionrelation',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases_relations', to='nursing_knowledges.diagnosis'),
        ),
        migrations.AddField(
            model_name='interventionrelation',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_relations', to='nursing_knowledges.interventioncontent'),
        ),
    ]
