# Generated by Django 3.2.8 on 2021-10-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0002_auto_20211021_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='connection',
            field=models.ManyToManyField(blank=True, to='nursing_knowledges.Disease'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='connection',
            field=models.ManyToManyField(blank=True, to='nursing_knowledges.Diagnosis'),
        ),
    ]
