# Generated by Django 3.2.8 on 2022-03-18 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0003_delete_diagnosisrelateddiagnoses'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRelatedDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_diagnosis_name', models.CharField(max_length=50)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_related_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('target_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiagnosisRelatedDiagnoses', to='nursing_knowledges.diagnosissmallcategory')),
            ],
        ),
    ]
