# Generated by Django 3.2.8 on 2021-10-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0003_auto_20211021_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='_nursing_knowledges_diagnosis_connection_+', to='nursing_knowledges.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='connection',
            field=models.ManyToManyField(blank=True, related_name='_nursing_knowledges_disease_connection_+', to='nursing_knowledges.Disease'),
        ),
    ]
