# Generated by Django 3.2.8 on 2021-10-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0005_auto_20211021_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnosise'},
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='connection',
        ),
    ]
