# Generated by Django 3.2.8 on 2022-03-22 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0007_auto_20220322_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisSmallCategoryStarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('diagnosis_small_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosissmallcategory')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='diagnosissmallcategory',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_diagnoses', through='nursing_knowledges.DiagnosisSmallCategoryStarInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
