# Generated by Django 3.2.8 on 2021-10-21 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0007_auto_20211021_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'verbose_name': 'Diagnose'},
        ),
    ]
