# Generated by Django 3.2.8 on 2021-10-21 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0008_alter_diagnosis_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='connection',
        ),
        migrations.CreateModel(
            name='DiseaseDiagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosis')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.disease')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosis')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.disease')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diseases',
            field=models.ManyToManyField(blank=True, through='nursing_knowledges.DiagnosisDiseases', to='nursing_knowledges.Disease'),
        ),
        migrations.AddField(
            model_name='disease',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, through='nursing_knowledges.DiseaseDiagnoses', to='nursing_knowledges.Diagnosis'),
        ),
    ]
