# Generated by Django 3.2.8 on 2021-10-21 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0010_auto_20211021_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Diagnose',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosis')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.disease')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, through='nursing_knowledges.DiseaseConnect', to='nursing_knowledges.Diagnosis'),
        ),
        migrations.CreateModel(
            name='DiagnosisConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosis')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.disease')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diseases',
            field=models.ManyToManyField(blank=True, through='nursing_knowledges.DiagnosisConnect', to='nursing_knowledges.Disease'),
        ),
        migrations.AlterField(
            model_name='interventionrelation',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_relations', to='nursing_knowledges.diagnosis'),
        ),
        migrations.AlterField(
            model_name='interventionrelation',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_relations', to='nursing_knowledges.disease'),
        ),
        migrations.DeleteModel(
            name='NursingKnowledge',
        ),
    ]
