# Generated by Django 3.2.8 on 2022-03-24 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0011_rename_diagnosistoother_diagnosistodisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosissmallcategorystarinfo',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_small_category_star_infoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diseasesmallcategorystarinfo',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_small_category_star_infoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgeedithistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
