# Generated by Django 3.2.8 on 2022-04-06 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0012_auto_20220324_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasesmallcategory',
            name='disease_large_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseasesmallcategory_by_large', to='nursing_knowledges.diseaselargecategory'),
        ),
        migrations.AlterField(
            model_name='diseasesmallcategory',
            name='disease_medium_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseasesmallcategory_by_medium', to='nursing_knowledges.diseasemediumcategory'),
        ),
        migrations.CreateModel(
            name='DiseaseSmallCategoryEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField(blank=True, default='', max_length=3000)),
                ('cause', models.TextField(blank=True, default='', max_length=3000)),
                ('symptom', models.TextField(blank=True, default='', max_length=3000)),
                ('diagnosis_and_checkup', models.TextField(blank=True, default='', max_length=3000)),
                ('treatment', models.TextField(blank=True, default='', max_length=3000)),
                ('nursing', models.TextField(blank=True, default='', max_length=3000)),
                ('changed_word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease_large_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseasesmallcategoryedithistory_by_large', to='nursing_knowledges.diseaselargecategory')),
                ('disease_medium_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseasesmallcategoryedithistory_by_medium', to='nursing_knowledges.diseasemediumcategory')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
