# Generated by Django 3.2.8 on 2021-10-21 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0012_auto_20211021_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionrelation',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_relations', to='nursing_knowledges.diseaseconnect'),
        ),
    ]
