# Generated by Django 3.2.8 on 2021-11-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0014_auto_20211021_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventionrelation',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='interventionrelation',
            name='intervention',
        ),
        migrations.DeleteModel(
            name='InterventionContent',
        ),
        migrations.DeleteModel(
            name='InterventionRelation',
        ),
    ]
