# Generated by Django 3.2.8 on 2021-11-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0015_auto_20211115_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='content',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
