# Generated by Django 3.2.8 on 2022-04-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0017_alter_diseasesmallcategoryedithistory_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasesmallcategoryedithistory',
            name='disease_small_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasesmallcategory'),
        ),
        migrations.AlterField(
            model_name='diseasesmallcategoryedithistory',
            name='version',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
