# Generated by Django 3.2.8 on 2021-11-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0019_alter_disease_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='intervention_content',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
