# Generated by Django 3.2.8 on 2021-11-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0020_diagnosis_intervention_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='content',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
