# Generated by Django 3.2.8 on 2021-11-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0021_alter_disease_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='content',
            field=models.TextField(max_length=3000, unique=True),
        ),
    ]
