# Generated by Django 3.2.8 on 2022-04-06 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0022_alter_knowledgeedithistory_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasesmallcategoryedithistory',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
