# Generated by Django 3.2.8 on 2021-11-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0022_alter_disease_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisconnect',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='diagnosisconnect',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='diagnoses',
        ),
        migrations.RemoveField(
            model_name='diseaseconnect',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='diseaseconnect',
            name='disease',
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='DiagnosisConnect',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='DiseaseConnect',
        ),
    ]
