# Generated by Django 3.2.8 on 2021-11-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursing_knowledges', '0023_auto_20211120_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(max_length=3000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('intervention_content', models.TextField(default='', max_length=3000)),
                ('diseases', models.ManyToManyField(blank=True, to='nursing_knowledges.Disease')),
            ],
            options={
                'verbose_name': 'Diagnose',
            },
        ),
    ]
