# Generated by Django 3.2.8 on 2021-11-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0024_diagnosis_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='diseases',
        ),
    ]
