# Generated by Django 3.2.8 on 2022-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0024_auto_20220406_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasesmallcategoryedithistory',
            name='is_change_related_diagnosis',
            field=models.BooleanField(default=False),
        ),
    ]
