# Generated by Django 3.2.8 on 2022-04-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0025_diseasesmallcategoryedithistory_is_change_related_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseasesmallcategoryedithistory',
            name='is_change_related_diagnosis',
        ),
    ]
