# Generated by Django 3.2.8 on 2021-11-20 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0026_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseLargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseMediumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('disease_large_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseaselargecategory')),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='disease_medium_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasemediumcategory'),
        ),
        migrations.AddField(
            model_name='disease',
            name='disease_medium_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasemediumcategory'),
        ),
    ]
