# Generated by Django 3.2.8 on 2022-04-07 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0026_remove_diseasesmallcategoryedithistory_is_change_related_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisSmallCategoryEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(blank=True, default='', max_length=3000)),
                ('intervention_content', models.TextField(blank=True, default='', max_length=3000)),
                ('changed_word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(blank=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('original_diagnosis_small_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_small_category_edit_histories', to='nursing_knowledges.diagnosissmallcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
