# Generated by Django 3.2.8 on 2021-11-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0027_auto_20211120_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_medium_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasemediumcategory'),
        ),
        migrations.AlterField(
            model_name='diseasemediumcategory',
            name='disease_large_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseaselargecategory'),
        ),
    ]
