# Generated by Django 3.2.8 on 2022-04-07 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0027_diagnosissmallcategoryedithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRelatedDiagnosisEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_diagnosis_name', models.CharField(max_length=50)),
                ('intervention_content', models.TextField(blank=True, default='', max_length=3000)),
                ('diagnosis_small_category_edit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_small_category_related_diagnosis_edit_histories', to='nursing_knowledges.diagnosissmallcategoryedithistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
