# Generated by Django 3.2.8 on 2021-11-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0029_auto_20211120_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaselargecategory',
            name='content',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='diseasemediumcategory',
            name='content',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='connection',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosis'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.disease'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='disease_medium_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasemediumcategory'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='intervention_content',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='disease',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
