# Generated by Django 3.2.8 on 2022-04-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0029_auto_20220407_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosissmallcategoryedithistory',
            name='is_rollbacked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diseasesmallcategoryedithistory',
            name='is_rollbacked',
            field=models.BooleanField(default=False),
        ),
    ]
