# Generated by Django 3.2.8 on 2021-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0030_auto_20211120_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='intervention_content',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='disease',
            name='content',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
