# Generated by Django 3.2.8 on 2021-11-20 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0031_auto_20211120_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseSmallCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(default='', max_length=3000)),
            ],
        ),
        migrations.RemoveField(
            model_name='connection',
            name='disease',
        ),
        migrations.AlterField(
            model_name='diseasemediumcategory',
            name='disease_large_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_medium_categories', to='nursing_knowledges.diseaselargecategory'),
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.AddField(
            model_name='diseasesmallcategory',
            name='disease_medium_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_small_categories', to='nursing_knowledges.diseasemediumcategory'),
        ),
        migrations.AddField(
            model_name='connection',
            name='disease_small_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasesmallcategory'),
        ),
    ]
