# Generated by Django 3.2.8 on 2022-04-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0031_auto_20220411_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KnowledgeEditHistory',
        ),
    ]
