# Generated by Django 3.2.8 on 2021-11-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0032_auto_20211120_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connection',
            new_name='DiagnosisToOther',
        ),
        migrations.AlterField(
            model_name='diseaselargecategory',
            name='content',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='diseasemediumcategory',
            name='content',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='diseasesmallcategory',
            name='content',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
