# Generated by Django 3.2.8 on 2022-04-11 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0032_delete_knowledgeedithistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedKnowledgeEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_diagnosis_edit_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosissmallcategoryedithistory')),
                ('reported_disease_edit_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasesmallcategoryedithistory')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
