# Generated by Django 3.2.8 on 2021-11-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0033_auto_20211120_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaselargecategory',
            name='content',
        ),
        migrations.RemoveField(
            model_name='diseasemediumcategory',
            name='content',
        ),
    ]
