# Generated by Django 3.2.8 on 2021-11-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0034_auto_20211120_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='intervention_content',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
