# Generated by Django 3.2.8 on 2021-12-21 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0035_alter_diagnosis_intervention_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisInterventionAlpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=3000)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosis')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasesmallcategory')),
            ],
        ),
    ]
