# Generated by Django 3.2.8 on 2021-12-21 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0036_diagnosisinterventionalpha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisinterventionalpha',
            name='disease',
        ),
        migrations.AddField(
            model_name='diagnosisinterventionalpha',
            name='disease_medium_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasemediumcategory'),
        ),
        migrations.AddField(
            model_name='diagnosisinterventionalpha',
            name='disease_small_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diseasesmallcategory'),
        ),
    ]
