# Generated by Django 3.2.8 on 2021-12-26 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0037_auto_20211221_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasesmallcategory',
            old_name='content',
            new_name='definition',
        ),
        migrations.AddField(
            model_name='diseasesmallcategory',
            name='diagnosis_and_checkup',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='diseasesmallcategory',
            name='nursing',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='diseasesmallcategory',
            name='symptom',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='diseasesmallcategory',
            name='treatment',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='diagnosisinterventionalpha',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alphas', to='nursing_knowledges.diagnosis'),
        ),
    ]
