# Generated by Django 3.2.8 on 2022-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0040_knowledgeedithistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeedithistory',
            name='changed_word_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='knowledgeedithistory',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
