# Generated by Django 3.2.8 on 2022-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0041_auto_20220223_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeedithistory',
            name='is_change_relation',
            field=models.BooleanField(default=False),
        ),
    ]
