# Generated by Django 3.2.8 on 2022-02-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0042_knowledgeedithistory_is_change_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgeedithistory',
            old_name='is_change_relation',
            new_name='is_change_relation_diagnosis',
        ),
    ]
