# Generated by Django 3.2.8 on 2022-02-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0043_rename_is_change_relation_knowledgeedithistory_is_change_relation_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgeedithistory',
            name='is_change_relation_diagnosis',
        ),
    ]
