# Generated by Django 3.2.8 on 2022-03-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0046_remove_knowledgeedithistory_is_change_relation_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='definition',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
