# Generated by Django 3.2.8 on 2022-03-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0047_diagnosis_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='related_diagnoses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing_knowledges.diagnosis'),
        ),
    ]
