# Generated by Django 3.2.8 on 2022-03-03 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0050_alter_diagnosis_related_diagnoses'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRelatedDiagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_diagnosis', to='nursing_knowledges.diagnosis')),
                ('like_users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like_related_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('to_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_diagnosis', to='nursing_knowledges.diagnosis')),
            ],
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='related_diagnoses',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='related_diagnoses',
            field=models.ManyToManyField(blank=True, through='nursing_knowledges.DiagnosisRelatedDiagnoses', to='nursing_knowledges.Diagnosis'),
        ),
    ]
