# Generated by Django 3.2.8 on 2022-03-03 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0051_auto_20220304_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosisrelateddiagnoses',
            name='like_users',
        ),
        migrations.AddField(
            model_name='diagnosisrelateddiagnoses',
            name='like_users',
            field=models.ManyToManyField(related_name='like_related_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
    ]
