# Generated by Django 3.2.8 on 2022-03-09 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nursing_knowledges', '0052_auto_20220304_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisLargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='diagnosisrelateddiagnoses',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_related_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiagnosisMediumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('diagnosis_large_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_medium_categories', to='nursing_knowledges.diagnosislargecategory')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_medium_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_medium_categories', to='nursing_knowledges.diagnosismediumcategory'),
        ),
    ]
