# Generated by Django 3.2.8 on 2022-03-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0053_auto_20220309_2208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnosis',
            new_name='DiagnosisSmallCategory',
        ),
    ]
