# Generated by Django 3.2.8 on 2022-03-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_knowledges', '0054_rename_diagnosis_diagnosissmallcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosissmallcategory',
            options={},
        ),
        migrations.AddField(
            model_name='diseasesmallcategory',
            name='disease_large_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_small_categories_by_large', to='nursing_knowledges.diseaselargecategory'),
        ),
        migrations.AlterField(
            model_name='diseasesmallcategory',
            name='disease_medium_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease_small_categories_by_medium', to='nursing_knowledges.diseasemediumcategory'),
        ),
    ]
